DWAPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 1.2  # x轴线速度最大值 m/s
  min_vel_x: 0.0  
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_vel_trans:  1.0   # 最大线速度 m/s
  min_vel_trans:  0.02   # 最小线速度，须大于0
  max_rot_vel : 157.0    # 最大转动速度 rad/s 绝对值
  min_rot_vel : 0.2
  acc_lim_x: 0.8         # 最大加速度  m/s2  2.5
  acc_lim_y: 0.0
  acc_lim_th: 0.08        # 最大角加速度  rad/s2  31
# Goal Tolerance Parametes
  xy_goal_tolerance: 0.02           # 终点误差容忍大小 m
  yaw_goal_tolerance: 1.0           # 终点误差容忍大小 rad
  latch_xy_goal_tolerance: false    # 到达终点后调整姿态
# Forward Simulation Parameters
  sim_time: 1.0
  sim_granularity: 0.025
  vx_samples: 20
  vy_samples: 1
  vth_samples: 20
  # controller_frequency: 5.0
# Trajectory Scoring Parameters
  path_distance_bias: 8.0       # 路径距离权重 64.0
  goal_distance_bias: 6.0        # 终点距离权重 12.0
  occdist_scale: 4.0             # 障碍物距离权重  0.5
  forward_point_distance: 0.3    # 前视距离 0.26
  stop_time_buffer: 0.12          # 避障时间缓冲 0.05
  scaling_speed: 0.25            # 速度缩放 m/s 绝对值
  max_scaling_factor: 0.22        # 最大速度缩放因子
  publish_cost_grid: false       # 发布代价地图
# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05     # 振荡重置距离
# Debugging
  publish_traj_pc: true            # 发布轨迹点云
  publish_cost_grid_pc: true       # 发布代价地图点云

# TrajectoryPlannerROS:
#   max_vel_x: 1
#   min_vel_x: 0.1
#   max_vel_theta:  1.0
#   min_vel_theta: -1.0
#   min_in_place_vel_theta: 1.0
#   acc_lim_x: 1.0
#   acc_lim_y: 0.0
#   acc_lim_theta: 0.6
# # Goal Tolerance Parameters
#   xy_goal_tolerance: 0.10
#   yaw_goal_tolerance: 0.05
# # Differential-drive robot configuration
#   holonomic_robot: false
# # Forward Simulation Parameters
#   sim_time: 0.8
#   vx_samples: 18
#   vtheta_samples: 20
#   sim_granularity: 0.05