obstacle_range: 5.0
raytrace_range: 1.0

robot_radius: 0 #.155

inflation_radius: 0.2       # 0.01/8/.13
cost_scaling_factor: 12     #15.0

# map_type: costmap
observation_sources: scan
scan: {sensor_frame: laser_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
