local_costmap:
  local_frame: odom
  robot_base_frame: base_footprint

  update_frequency: 25.0
  publish_frequency: 20.0
  transform_tolerance: 1.0

  static_map: true
  rolling_window: true
  width: 0.8
  height: 0.8
  resolution: 0.03
  